services:
  front:
    container_name: front
    image: front
    build:
      context: ./front
      dockerfile: front.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    depends_on:
      - back

  back:
    container_name: back
    image: back
    build:
      context: ./back
      dockerfile: back.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front

  seed:
    container_name: seed
    build:
      context: ./seed
      dockerfile: seed.dockerfile
    depends_on:
      - back
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public

volumes:
  pgdata: {}
